### ISSUE TITLE
typo in autocomplete.js

### ISSUE THREAD

**Issue by siege-16** [erossini/BlazorAutocomplete#1]
In the js located at [this line](https://github.com/erossini/BlazorAutocomplete/blame/84ff527a1f7e2ae0b3c96d271bea2ac457b13de8/src/wwwroot/js/autocomplete.js#L80), I noticed a small typo: 
`AutoComplete.onOutsideClickClear(searchTextElement);`
which should actually be 
`autocomplete.onOutsideClickClear(searchTextElement);`

I encountered an issue when integrating two instances of the component on a single Razor page; the dropdown functionality was not operating as expected. However, Thank you for making your code available to the community!

**Comment by erossini** [comment]
Thank you so much!

**Comment by mouseba11** [comment]
The bug remains in the Nuget Package its now "autoComplete" at line 80 should probably be "autocomplete" - works perfectly in my Blazor project up until that point though :)

**Comment by erossini** [comment]
Oh sorry, another update in coming...
